# Generated by Django 3.2.6 on 2021-09-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('kitchen_area', models.IntegerField(choices=[('Pantry', 'Pantry'), ('Fridge', 'Fridge'), ('Freezer', 'Freezer')])),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
